---
version: '3.8'


services:
  db:
    image: metosin/training-musicbrainz-db:latest
    init: true
    restart: always
    ports:
      - 127.0.0.1:5432:5432

  server:
    image: koulutus:server
    init: true
    restart: always
    ports:
      - 127.0.0.1:8080:8080
  
  web:
    image: koulutus:web
    init: true
    restart: always
    ports:
      - 127.0.0.1:8000:80
